sudo: required
services: 
  - docker

before_install:
  - docker build -t swarnim1007/docker-react -f Docker.dev .

script: 
  - docker run swarnim1007/docker-react npm run start -- --coverage
  - travis_wait 30 npm test

